spring.datasource.url=jdbc:mysql://localhost:3306/petcare
spring.datasource.username=petcare_user
spring.datasource.password=PetCareSenha123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true